version: '3'
services:
  filewatcher:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "9229:9229"
    command: 
      - node
      - "--inspect-brk=0.0.0.0"
      - "app.js" 
    restart: always
    volumes:
      - ./watch_folder:/usr/src/app/watch_folder
      - ./export_folder:/usr/src/app/export_folder
