version: '3'
services:
  pdfImageConverter:
    image: tobiasw/pdf-image-watcher:latest
    container_name: pdf-image-watcher
    volumes: 
        - ./export-folder:/usr/src/app/export_folder
        - ./import-folder-image-conversion:/usr/src/app/watch_folder
    restart: always
  OCRmyPDF:
    image: tobiasw/ocrmypdf-watcher:latest
    container_name: ocrmypdf-watcher
    volumes:
        - ./export-folder:/application/export-folder
        - ./import-folder-ocr:/application/watch-folder
    restart: always
  SAMBA:
     image: dperson/samba
     container_name: samba
     environment:
      TZ: 'EST5EDT'
     networks:
       - default
     ports:
       - "137:137/udp"
       - "138:138/udp"
       - "139:139"
       - "445:445"
     volumes:
       - ./import-folder-ocr:/mount/hot-folder
       - ./export-folder:/mount/archive
       - ./import-folder-image-conversion:/mount/hot-folder-image-conversion
     restart: always
     command: '-g "log level = 2" -n -r -S -u "scanner;password;1000" -s "Download_Bilder;/mount/hot-folder-image-conversion;yes;no;yes" -s "Upload;/mount/hot-folder;yes;no;yes" -s "Download;/mount/archive;yes;no;yes"'
